steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/battleos/battleos:$COMMIT_SHA'
      - '-t'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/battleos/battleos:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Push the image to the registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_AR_HOSTNAME/$_AR_PROJECT_ID/battleos/battleos:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_AR_HOSTNAME/$_AR_PROJECT_ID/battleos/battleos:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '$_SERVICE_NAME'
      - '--image=$_AR_HOSTNAME/$_AR_PROJECT_ID/battleos/battleos:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--platform=managed'
      - '--quiet'

substitutions:
  _SERVICE_NAME: battleos
  _DEPLOY_REGION: europe-west1

options:
  logging: CLOUD_LOGGING_ONLY
